### PR TITLE
74x

### PR DESCRIPTION
**Pull request by d-salerno**

### CODE REVIEW

**Comment by jpata** [comment]
This is already implemented.

**Comment by d-salerno** [comment]
HI Joosep, not all of this has been implemented... In particular the "ThreeQuarkLost=3, FourQuarkLost=4, FiveQuarkLost=5" and associated code.
Also https://github.com/bianchini/Code/blob/master/src/Integrand.cpp#L2077 should be corrected to allow the pT range to go beyond 2*30 GeV, either as I have suggested or some other way.

**Comment by jpata** [comment]
OK, sorry, this was not clear to me, I just saw the two small bugfixes being in. Please, can you make a clean PR against the master, no other changes?

**Comment by d-salerno** [comment]
OK, I'll give it a go. I'll try to make two separate PRs.

**Comment by d-salerno** [comment]
Ok, it all comes up in the same PR #19  - two different commits though.

**Comment by jpata** [comment]
Can we close this now? Preparing for 80X...

**Comment by d-salerno** [comment]
I think we can reject this one and accept PR #19 instead. Which I see is done - so it's ok to reject this!

**Comment by jpata** [comment]
#19 is already merged since a while, so I will close this one.

**Pull request closed without merging**
